# Generated by Django 2.2 on 2019-10-27 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_auto_20191027_1157'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestAdminModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.URLField()),
            ],
        ),
    ]
