# Generated by Django 2.2 on 2019-10-27 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_testadminmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TestAdminModel',
        ),
    ]
