# Generated by Django 2.2 on 2019-10-27 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_delete_testadminmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='is_visible',
            field=models.BooleanField(default='True'),
        ),
    ]
