# Generated by Django 2.2 on 2019-10-27 18:20

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_remove_item_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='slug',
            field=autoslug.fields.AutoSlugField(default="populate_from='title'", editable=False, populate_from='title'),
            preserve_default=False,
        ),
    ]
