version: 0.2

phases:
  install:
    commands:
      - ECR_REPOSITORY_URI=680696743786.dkr.ecr.eu-central-1.amazonaws.com/mkokocha-kupse
      - NOW=$(date +"%Y%m%d_%H%M%S")
      - TAG_NAME=$ECR_REPOSITORY_URI:$NOW
  pre_build:
    commands:
      - $(aws ecr get-login --region eu-central-1 --no-include-email)
  build:
    commands:
      - docker build -f Dockerfile -t $TAG_NAME .
  post_build:
    commands:
      - docker push $TAG_NAME

artifacts:
  files:
    - kupse-img-def.json