version: "3.8"

services:
  web:
    build: .
    command: bash -c "python manage.py migrate --noinput && python manage.py runserver 0.0.0.0:8000"
    environment:
      - REDIS_LOCATION=redis://redis:6379/
      - DB_HOST=db
      - DB_PORT=5432
      - DB_PASSWORD=my_db@123
      - DB_USER=postgres
      - DB_NAME=my_db
    volumes:
      - $PWD/sqlite-data:/sqlite-data/
      - $PWD/Kupse:/code/
    networks:
      - kupse-dev
    ports:
      - "8000:8000"
    links:
      - redis
      - db
  redis:
    image: 'redis:latest'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    networks:
      - kupse-dev
    ports:
      - "6379:6379"
    volumes:
      - $PWD/redis-data:/data
  db:
    build:
      context: .
      dockerfile: Dockerfile.db
    environment: 
      - POSTGRES_PASSWORD=my_db@123
      - DB_NAME=my_db
      - DB_USER=postgres
    networks:
      - kupse-dev
    ports:
      - "5432:5432"
    # volumes:
    #   - $PWD/postgres-data:/var/lib/postgresql/data


networks:
  kupse-dev:
    name: kupse-dev